### ISSUE TITLE
unfiltered.jetty.Server.local not binding on Heroku

### ISSUE THREAD

**Issue by rgladwell** [unfiltered/unfiltered#290]
For some reason, when I use `unfiltered.jetty.Server.local` the started service does not seem to correctly bind to the correct network interface on Heroku and I get:

```
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

If I used the deprecated `unfiltered.jetty.Http` object this seems to work:

https://github.com/rgladwell/is-aws-api/blob/030261bc620d1f1f5af2d9aaa893cfcf902b2e31/src/main/scala/me/gladwell/aws/API.scala

**Comment by chrislewis** [comment]
Hello Ricardo,

I'm not immediately sure what the problem is, but after a glance, one
obvious difference between those two calls is that Server.local binds to
the local interface
<https://github.com/unfiltered/unfiltered/blob/48a56d5a233a567eb6db5f74a932a9ad48643d74/jetty/src/main/scala/bindings.scala#L24-L25>,
while Http#apply(Int) binds to all
<https://github.com/unfiltered/unfiltered/blob/48a56d5a233a567eb6db5f74a932a9ad48643d74/jetty/src/main/scala/http.scala#L20>.
If your goal is to bind to all then you can use Server.http
<https://github.com/unfiltered/unfiltered/blob/48a56d5a233a567eb6db5f74a932a9ad48643d74/jetty/src/main/scala/bindings.scala#L21>
instead.

On Tue, Feb 3, 2015 at 7:46 AM, Ricardo Gladwell <notifications@github.com>
wrote:

> For some reason, when I use unfiltered.jetty.Server.local the started
> service does not seem to correctly bind to the correct network interface on
> Heroku and I get:
>
> Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
>
> If I used the deprecated unfiltered.jetty.Http object this seems to work:
>
>
> https://github.com/rgladwell/is-aws-api/blob/030261bc620d1f1f5af2d9aaa893cfcf902b2e31/src/main/scala/me/gladwell/aws/API.scala
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/unfiltered/unfiltered/issues/290>.
>



-- 
-chris

**Comment by rgladwell** [comment]
Cool that worked, thanks!
