### ISSUE TITLE
The current status of the project 

### ISSUE THREAD

**Issue by ahmedaswai** [unfiltered/unfiltered#305]
Is there is any plans to update the library or upgrade to add more features on it because I don't see any current discussions about this project which make me feel confused about using it in  my new project?

**Comment by chrislewis** [comment]
The issue tracker is not an appropriate place for general questions. For that, please use the [google group](https://groups.google.com/forum/#!forum/unfiltered-scala), as stated in the Readme of this project.

This is an open source project: we are developers working on this as a volunteer effort because we want it to exist. Yes, there are both plans and actions to further the library, though the actions have been much less frequent over the last several months. If there are features you would like to see, please submit a pull request. If you have run into bugs you would like fixed, please submit a pull request. In the less ideal but still valid case, open an issue describing what you'd like to see and, if we agree it's a good addition, we'll implement it.

If you are concerned that this project doesn't have a full time staff for either development or support, don't use it. Both are true and are unlikely to change. However, if the library suits your needs and you are happy with a network of open source developers and users alike working to better a library that makes our lives easier, use it. In either case, good luck on your projects!
