### ISSUE TITLE
Converting filter to servlet

### ISSUE THREAD

**Issue by dmos62** [unfiltered/unfiltered#310]
I'm running into bugs in Google App Engine development server where it does not play with filters well (in certain [cases](https://code.google.com/p/googleappengine/issues/detail?id=9859)). Therefore, I'm looking for ways to convert my Unfiltered plans/filters to servlets. That is my main question. What does it amount to to wrap/convert Unfiltered filters to servlets?

A sidelines question would be, why filters instead of servlets, or rather, why only filters? According to the servlet specification (to my understanding), servlets, as opposed to filters, are meant to be the primary servers of content. Note I am not attacking Unfiltered's design, it's just a question that popped up in my mind.

**Comment by chrislewis** [comment]
Hi @dmos62. Please use the [mailing list](https://groups.google.com/forum/#!forum/unfiltered-scala) for questions like this.

That thread you shared lists some potential workarounds. The bug here is in the appengine development kit and so that is where it should be solved. That said, here are responses to your questions:

#### What does it amount to to wrap/convert Unfiltered filters to servlets?

This cannot be done generally without crippling the intended behavior of Unfiltered. If you wish to proceed anyway (I recommend against that), see how Plans are [implemented for filters](https://github.com/unfiltered/unfiltered/blob/0.9.0/filter/src/main/scala/plans.scala). You should clearly see how it works and why this would be a crippling change.

#### why filters instead of servlets, or rather, why only filters?

One of the cruxes of Unfiltered's design is the reliance on [pattern matching](http://docs.scala-lang.org/tutorials/tour/pattern-matching.html) to route requests to appropriate blocks of code. This works by defining the intents in terms of partial functions and, when the pattern fails to match, permitting the server runtime to transfer control to another one, if an appropriate one exists. Servlet filters permit the optional transfer of control, servlets do not. This is why Unfiltered (the JEE/servlet flavor) is implemented in terms of filters, not servlets, and why it must be so.
